export type FactsTable = {
  htmlId?: string;
  tag?: string;
  period?: string;
  axes?: unknown;
  members?: Array<string> | string | null;
  measure?: unknown;
  scale?: number | null;
  decimals?: unknown;
  files?: string | null;
  order?: number;
  balance?: string;
  value?: string;
  dimensions?: unknown;
  contextref?: unknown;
  isHidden?: unknown;
  isHtml?: number;
  isNegative?: number;
  isNumeric?: number;
  isText?: number;
  isCustom?: number;
  standardLabel?: string;
  labels?: unknown;
  calculations?: unknown;
  references?: unknown;
};
