export type FactsTable = {
  id?: string;
  tag?: string;
  period?: string;
  axes?: unknown;
  members?: Array<string> | string | null;
  measure?: unknown;
  scale?: number | null;
  decimals?: unknown;
  files?: string | null;
  order: number;
  balance?: string;
  value?: string;
  dimensions?: unknown;
  dimensionsValue?: Array<string>;
  contextref?: unknown;
  isHidden?: unknown;
  isHtml?: number;
  isNegative?: number;
  isNumeric?: number;
  isText?: number;
  isCustom?: number;
  standardLabel?: string;
  labels: Array<string>;
  calculations?: unknown;
  references?: Array<string>;
  type?: string;
  isActive: boolean;
  isHighlight: boolean;
};
