export const Scale = {
    0: `Zero`,
    1: `Tens`,
    2: `Hundreds`,
    3: `Thousands`,
    4: `Ten thousands`,
    5: `Hundred thousands`,
    6: `Millions`,
    7: `Ten Millions`,
    8: `Hundred Millions`,
    9: `Billions`,
    10: `Ten Billions`,
    11: `Hundred Billions`,
    12: `Trillions`,
    '-1': `Tenths`,
    '-2': `Hundredths`,
    '-3': `Thousandths`,
    '-4': `Ten Thousandths`,
    '-5': `Hundred Thousandths`,
    '-6': `Millionths`,
  };
  